# CodeRabbit Configuration
# Front-line automated PR triage - runs first before Ollama/Claude

# Language and framework awareness
language: en-US
early_access: true

# Review settings
reviews:
  # Request changes only for critical issues
  request_changes_workflow: true

  # High-level PR summary
  high_level_summary: true

  # Detailed file summaries
  poem: false

  # Review profile
  profile: assertive

  # Auto-review on PR events
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  # Scope of review
  tools:
    biome:
      enabled: true
    github-checks:
      enabled: true
    markdownlint:
      enabled: false
    languagetool:
      enabled: false

  # Path-specific instructions
  path_instructions:
    - path: "game/src/**/*.{js,jsx}"
      instructions: |
        - Follow Astro + Solid.js patterns
        - Use Matter.js for physics (proven in POC)
        - Procedural rendering with Canvas 2D API
        - Check for proper DDL manifest loading
        - Warm aesthetic consistency (BRAND.md)

    - path: "client/src/**/*.{ts,tsx}"
      instructions: |
        - Legacy React Three Fiber code (being migrated)
        - Check for migration opportunities to Astro + Solid.js
        - Flag static asset imports (should be procedural)

    - path: "e2e/**/*.spec.ts"
      instructions: |
        - Verify Playwright best practices
        - Check for proper test isolation
        - Ensure video capture is configured correctly
        - Validate game state API usage

    - path: ".github/workflows/**/*.yml"
      instructions: |
        - Validate GitHub Actions syntax
        - Check for proper secret handling
        - Verify workflow dependencies and triggers
        - Ensure proper permissions are set
        - Node.js version must be 25.x

# Chat settings
chat:
  auto_reply: true

# Knowledge base
knowledge_base:
  # Game-specific patterns (updated for Astro + Solid.js architecture)
  learnings:
    scope: "auto"
    items:
      - "Use pnpm exclusively, never npm or yarn"
      - "Procedural rendering with Canvas 2D, no static PNG/MP4 imports"
      - "Matter.js for physics simulation (proven in POC)"
      - "Solid.js for reactive UI components"
      - "Astro for static site generation"
      - "JavaScript preferred over TypeScript for simplicity"
      - "DDL-driven architecture with JSON manifests"
      - "Warm Redwall-inspired aesthetic (BRAND.md)"
