# pnpm workspace configuration
# See: https://pnpm.io/workspaces

packages:
  # Main application packages
  - "."
  - "packages/*"

# Ignore certain built dependencies to avoid compilation issues
ignoredBuiltDependencies:
  - bufferutil
  - esbuild
